# Creat by Abraão Silva
# Date 12 Nov 2018 
version: '3'
services:
  postgresql: # BANCO DE DADOS POSTGRESQL
    image: orchardup/postgresql:latest
    container_name: postgresql 
    environment:
      - POSTGRESQL_USER=sonar
      - POSTGRESQL_PASS=xaexohquaetiesoo
      - POSTGRESQL_DB=sonar
    volumes:
      - "$PWD/postgresql:/var/lib/postgresql"

  sonarqube: # SONARQUBE
    # use UID here
    # user: 1004:1004
    image: sonarqube:6.7
    container_name: sonarqube
    restart: always  
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=xaexohquaetiesoo
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
    volumes:
      - "$PWD/sonarqube/sonarqube-conf:/opt/sonarqube/conf"
      - "$PWD/sonarqube/sonarqube-data:/opt/sonarqube/data"
      - "$PWD/sonarqube/sonarqube-data:/opt/sonarqube/logs"
      - "$PWD/sonarqube/sonarqube-data:/opt/sonarqube/temp"
      - "$PWD/sonarqube/sonarqube-extensions:/opt/sonarqube/extensions"
      - "$PWD/sonarqube/data/sonarqube/bundled_plugins:/opt/sonarqube/lib/bundled-plugins"
    ports:
      - "3000:9000"
