# Creat by Abraão Silva
# Date 12 Nov 2018
version: '3'
services:
   sonarqube: # SONARQUBE
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    networks:
      - sonarnet
    links:
      - db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - "$PWD/sonarqube/sonarqube-conf:/opt/sonarqube/conf"
      - "$PWD/sonarqube/sonarqube-data:/opt/sonarqube/data"
      - "$PWD/sonarqube/sonarqube-data:/opt/sonarqube/logs"
      - "$PWD/sonarqube/sonarqube-data:/opt/sonarqube/temp"
      - "$PWD/sonarqube/sonarqube-extensions:/opt/sonarqube/extensions"
      - "$PWD/sonarqube/data/sonarqube/bundled_plugins:/opt/sonarqube/lib/bundled-plugins"
    ports:
      - "9000:9000"

   db: # BANCO DE DADOS POSTGRESQL
    image: postgres
    container_name: postgresql
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRESQL_USER=sonar
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "$PWD/postgresql:/var/lib/postgresql"
      - "$PWD/postgresql_data:/var/lib/postgresql/data"
networks:
  sonarnet:
